myenglish/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^testEng/', include('testEng.urls')),
    url(r'^', include('testEng.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testEng/urls.py
from django.conf.urls import url
from . import views

app_name = 'testEng'
urlpatterns = [
    # /testEng/
    url(r'^$', views.index, name = 'index'),

    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^register/$', views.UserFormView.as_view(), name = 'register'),

    url(r'^(?P<testQuestion_id>[0-9]+)/$', views.detail, name="detail"),

    url(r'^topic/$', views.gettopic, name = 'topic'),
    url(r'^topic/(?P<topic_id>[0-9]+)/$', views.detailtopic, name = 'detail-topic'),
    url(r'^topic/topicadd/$', views.TopicCreate.as_view(), name='topic-add'),
    url(r'^topic/createtopic/$', views.CreateTopicFormView.as_view(), name = 'createtopic'),
    url(r'^topic/(?P<pk>[0-9]+)/updatetopic/$', views.TopicUpdate.as_view(), name='topic-update'),
    url(r'^topic/(?P<pk>[0-9]+)/deletetopic/$', views.TopicDelete.as_view(), name='topic-delete'),

    url(r'^dictionary/$', views.dictionary, name = 'dictionary'),
    url(r'^dictionary/dictionaryTolearn/$', views.dictionaryTolearn, name = 'dictionaryTolearn'),
    url(r'^dictionary/wordadd/$', views.WordCreate.as_view(), name='word-add'),
    url(r'^dictionary/(?P<pk>[0-9]+)/updateword/$', views.WordUpdate.as_view(), name='word-update'),
    url(r'^dictionary/(?P<pk>[0-9]+)/deleteword/$', views.WordDelete.as_view(), name='word-delete'),
    url(r'^dictionary/createword/$', views.CreateWordFormView.as_view(), name = 'createword'),
    url(r'^dictionary/(?P<word_id>[0-9]+)/tolearn/$', views.tolearn, name='tolearn'),

    url(r'^testing/$', views.gettest, name = 'testing'),
    # url(r'^create_word/$', views.create_word, name='create_word'),
]
# <!--<form action="{% url '#' quest.id %}" method="post">-->

testEng/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import Permission, User

# Create your models here.
class testQuestion(models.Model):
    question = models.CharField(max_length=1000)
    multichoice = models.BooleanField()

    def __str__(self):
        return self.question

class optionAnswer(models.Model):
    id_question = models.ForeignKey(testQuestion, on_delete=models.CASCADE)
    content = models.CharField(max_length=1000)
    isCorrect = models.BooleanField()

    def __str__(self):
        return self.content

class category(models.Model):
    name = models.CharField(max_length=1000)

    def __str__(self):
        return self.name

class quest_cate(models.Model):
    id_question = models.ForeignKey(testQuestion, on_delete=models.CASCADE)
    id_category = models.ForeignKey(category, on_delete=models.CASCADE)

    def __str__(self):
        return self.id_question.question + ' - ' + self.id_category.name

class user(models.Model):
    name = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    email = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class topic(models.Model):
    name = models.CharField(max_length=1000)
    content = models.TextField(max_length=10000)
    user = models.ForeignKey(User, default=1)
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('testEng:topic')

class comment(models.Model):
    id_user = models.ForeignKey(User, on_delete=models.CASCADE)
    id_topic = models.ForeignKey(topic, on_delete=models.CASCADE)
    content = models.CharField(max_length = 1000)

    def __str__(self):
        return self.content


class word(models.Model):
    user = models.ForeignKey(User, default=1)
    name = models.CharField(max_length = 1000)
    meaning = models.CharField(max_length = 1000)
    pronunc = models.CharField(max_length = 1000)
    image = models.FileField()
    audio = models.FileField(default='')
    type = models.CharField(max_length = 1000)
    tolearn = models.BooleanField(default=False)
    # id_user = models.ForeignKey(user, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('testEng:dictionary')

class word_cate(models.Model):
    id_word = models.ForeignKey(word, on_delete=models.CASCADE, default=1)
    id_category= models.ForeignKey(category, on_delete=models.CASCADE)

    def __str__(self):
        return self.id_word.name + ' - ' + self.id_category.name

testEng/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import word, topic, comment

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class WordForm(forms.ModelForm):

    class Meta:
        model = word
        fields = ['name', 'meaning', 'pronunc', 'type', 'image', 'audio', 'tolearn']


class TopicForm(forms.ModelForm):

    class Meta:
        model = topic
        fields = ['name', 'content']

class CommentForm(forms.ModelForm):
    class Meta:
        model = comment
        fields = ['content']

testEng/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from django.views import generic
from .forms import  UserForm, WordForm, TopicForm, CommentForm
from .models import testQuestion, word, topic, optionAnswer, comment
from django.template import loader
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.http import JsonResponse, Http404
from django.db.models import Q
import random

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                # words = word.objects.filter(user=request.user)
                # return render(request, 'testEng/dictionary.html', {'all_words' : words})
                all_questions = testQuestion.objects.all()
                return render(request, 'testEng/index.html', {'all_questions' : all_questions, 'username': request.user})
            else:
                return render(request, 'testEng/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'testEng/login.html', {'error_message': 'Invalid login'})
    return render(request, 'testEng/login.html')

def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'testEng/login.html', context)

def index(request):
     if not request.user.is_authenticated():
        return render(request, 'testEng/login.html')
     else:
        # words = word.objects.filter(user=request.user)
        all_questions = testQuestion.objects.all()
        return render(request, 'testEng/index.html', {'all_questions' : all_questions, 'username' : request.user})
    # all_questions = testQuestion.objects.all()
    # template = loader.get_template('testEng/index.html')
    # return render(request, 'testEng/index.html', {'all_questions' : all_questions})

def detail(request, testQuestion_id):
    quest = get_object_or_404(testQuestion, pk=testQuestion_id)
    # optionAns = optionAnswer.objects.filter(testQuestion = quest)
    optionAns = []
    optionAnswers = optionAnswer.objects.all()
    for ans in optionAnswers:
        if ans.id_question == quest:
            optionAns.append(ans)
    return render(request, 'testEng/detail.html', {'quest' : quest, 'optionAns' : optionAns, 'username' : request.user})
    # res = "<h2> Details for question: "  + str(testQuestion_id) +"</h2>"
    # return HttpResponse(res)

def detailtopic(request, topic_id):
    curTopic = get_object_or_404(topic, pk=topic_id)
    comments = comment.objects.filter(id_topic=topic_id)

    if 'contentComment' in request.POST:
        newComment = comment(id_user = request.user, id_topic = curTopic, content = request.POST['contentComment'])
        # newComment.id_user = request.user
        # newComment.id_topic = curTopic
        # newComment.content = 'helloooooooooo'
        newComment.save()
        comments = comment.objects.filter(id_topic=topic_id)

    return render(request, 'testEng/detailTopic.html', {'curTopic': curTopic, 'comments': comments, 'username' : request.user})

def dictionary(request):
    if not request.user.is_authenticated():
        return render(request, 'testEng/login.html')
    else:
        all_words = word.objects.filter(user=request.user)
        return render(request, 'testEng/dictionary.html', {'all_words' : all_words, 'username' : request.user})

def dictionaryTolearn(request):
    if not request.user.is_authenticated():
        return render(request, 'testEng/login.html')
    else:
        all_words = word.objects.filter(user=request.user, tolearn = True)
        return render(request, 'testEng/dictionaryTolearn.html', {'all_words' : all_words, 'username' : request.user})

# def markTolearn(request):
#     all_words = word.objects.all()
#     try:
#         selected_word = all_words.get(pk=request.POST['curWord'])
#     except (KeyError, word.DoesNotExist):
#         return render(request, 'testEng/dictionary.html', {
#             'all_words' : all_words,
#             'error_message': "Error"
#         })
#     else:
#         selected_word.tolearn = True
#         selected_word.save()
#         return render(request, 'testEng/dictionary.html', {'all_words' : all_words})

def gettest(request):
    questions = testQuestion.objects.all()
    optionAnswers = optionAnswer.objects.all()
    # optionAns = []
    # for quest in questions:
    #     temp = []
    #     for ans in optionAnswers:
    #         if ans.id_question == quest:
    #             temp.append(ans)
    #     optionAns.append(temp)

    return render(request, 'testEng/testing.html', {'all_questions' : questions, 'optionAnswers':optionAnswers, 'username' : request.user})
    # return render(request, '#')

def gettopic(request):
    all_topics = topic.objects.all()
    return render(request, 'testEng/topic.html', {'all_topics' : all_topics, 'username': request.user})

class IndexView(generic.ListView):
    template_name = 'testEng/index.html'
    context_object_name = 'all_questions'
    def get_queryset(self):
        return testQuestion.objects.all()

class DetailView(generic.DetailView):
    model = testQuestion
    template_name = 'testEng/detail.html'

class UserFormView(View):
    form_class = UserForm
    template_name = 'testEng/registration_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form' : form, 'username' : request.user})

    #process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #return User Object
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    all_questions = testQuestion.objects.all()
                    return render(request, 'testEng/index.html', {'all_questions' : all_questions, 'username': request.user})
                    # return redirect('testEng:index', {'username': request.user})

        return render(request, self.template_name, {'form': form, 'username' : request.user})

class CreateWordFormView(View):
    form_class = WordForm
    template_name = 'testEng/word_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form' : form, 'username' : request.user})

    def post(self, request):
        # form = self.form_class(request.POST)
        form = self.form_class(request.POST or None, request.FILES or None)
        if form.is_valid():
            newword = form.save(commit=False)
            newword.user = request.user
            newword.image = request.FILES['image']
            newword.audio = request.FILES['audio']
            newword.save()
            return redirect('testEng:dictionary')
            #
            # return render(request, 'testEng/index.html', {'all_questions' : all_questions, 'username': request.user})
        return render(request, self.template_name, {'form' : form, 'username' : request.user})

class TopicCreate(CreateView):
    model = topic
    fields = ['name', 'content']





class CreateTopicFormView(View):
    form_class = TopicForm
    template_name = 'testEng/topic_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form' : form, 'username' : request.user})

    def post(self, request):
        form = self.form_class(request.POST or None, request.FILES or None)
        if form.is_valid():
            newtopic = form.save(commit=False)
            newtopic.user = request.user
            newtopic.save()
            return redirect('testEng:topic')
            # return render(request, 'testEng/index.html', {'all_questions' : all_questions, 'username': request.user})
        return render(request, self.template_name, {'form': form, 'username' : request.user})


class TopicUpdate(UpdateView):
    model = topic
    fields = ['name', 'content']

    def get_object(self, queryset=None):
        """ Hook to ensure object is owned by request.user. """
        obj = super(TopicUpdate, self).get_object()
        if not obj.user == self.request.user:
            raise Http404
        return obj

class TopicDelete(DeleteView):
    model = topic
    success_url = reverse_lazy('testEng:topic')

    def get_object(self, queryset=None):
        """ Hook to ensure object is owned by request.user. """
        obj = super(TopicDelete, self).get_object()
        if not obj.user == self.request.user:
            raise Http404
        return obj


class WordCreate(CreateView):
    model = word
    fields = ['name', 'meaning', 'pronunc', 'type', 'image', 'audio', 'tolearn']


class WordUpdate(UpdateView):
    model = word
    fields = ['name', 'meaning', 'pronunc', 'type','image', 'audio', 'tolearn']

class WordDelete(DeleteView):
    model = word
    success_url = reverse_lazy('testEng:dictionary')


def DeleteWord(request, word_id):
    u = word.objects.get(pk=word_id).delete()

testEng/templates/testEng/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}testEng{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'testEng/style.css' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'testEng/js/main.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle"data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand changeFont" href="{% url 'testEng:index' %}">
                TestEng
            </a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'testEng:index' %}">
                        <span class="glyphicon glyphicon-check" aria-hidden="true"></span>&nbsp;
                        testQuestions
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'testEng:dictionary' %}">
                        <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>&nbsp;
                        Dictionary
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'testEng:topic' %}">
                        <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>&nbsp;
                        Topic
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'testEng:createword' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Add word
                    </a>
                </li>

                <li class="">
                    <a href="{% url 'testEng:createtopic' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Add topic
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'testEng:logout_user' %}">
                        <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>&nbsp;
                        {% if username %}
                            {{ username }}
                        {% endif %}
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

testEng/templates/testEng/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
    <title>{% block title %}testEng{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'testEng/style.css' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand changeFont" href="#">
                TestEng
            </a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'testEng:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'testEng:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

testEng/templates/testEng/detailTopic.html
{% extends 'testEng/base.html' %}
{% block title %}Topic details{% endblock %}
{% block body %}
{% csrf_token %}
<div class="container">
    <div>
        <h3>{{ curTopic.name }} </h3>
        <p>
            {{ curTopic.content|linebreaksbr }}
        </p>
        <h6> Posted by: {{ curTopic.user }} </h6>

        <a href="{% url 'testEng:topic-update' curTopic.id %}">
            <button type="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-edit"></span>&nbsp; Edit
            </button>
        </a>

        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal">
            <span class="glyphicon glyphicon-trash"></span>&nbsp; Delete
        </button>

        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">

              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header label-warning">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">
                      <span class="glyphicon glyphicon-warning-sign"></span>&nbsp; Delete Topic
                  </h4>
                </div>
                <div class="modal-body">
                  <p>Do you want to delete the topic: {{ curTopic.name }}?</p>
                </div>
                <div class="modal-footer">
                    <form action="{% url 'testEng:topic-delete' curTopic.id %}" method="post" style="display: inline">
                        {% csrf_token %}
                        <input type="hidden" name="topic_id" value="{{curTopic.id}}"/>
                        <button type="submit" class="btn btn-danger btn-sm">
                            <span class="glyphicon glyphicon-trash"></span>&nbsp; Delete
                        </button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </form>
                </div>
              </div>

            </div>
          </div>

        <div class="row">
                <h2>Comments</h2>
            {% for comment in comments %}
                <div class="row-comment">
                    <div class="row-comment-content">
                        <h3>{{comment.content|linebreaksbr }}</h3>
                    </div>
                    <h5>commented by: {{comment.id_user}}</h5>
                </div>
            {% endfor %}
        </div>

        <div class="row">
            <form action="{% url 'testEng:detail-topic' curTopic.id %}" method="post" style="display: inline">
            {% csrf_token %}
                <div class="row">
                    <textarea name="contentComment" rows="4" cols="50"></textarea>
                </div>
                <button type="submit" class="btn btn-success btn-sm">
                    <span class="glyphicon glyphicon-plus"></span>&nbsp; Add Comment
                </button>
            </form>
        </div>

    </div>
</div>
{% endblock %}

testEng/templates/testEng/dictionary.html
{% extends 'testEng/base.html' %}
{% block title %}Dictionary{% endblock %}
{% block body %}

{% csrf_token %}
<div class="container">

<form action="{% url 'testEng:dictionaryTolearn' %}" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">
        <span class="glyphicon glyphicon-play"></span>&nbsp; Words to learn
    </button>
</form>

<form action="#" method="#">
        <ul>
            {% csrf_token %}
            {% for curWord in all_words %}
                <li>
                    <h3>{{curWord.name}}</h3>

                    <a href="{% url 'testEng:tolearn' curWord.id %}" class="btn-tolearn">
                        <span class="glyphicon glyphicon-star {% if curWord.tolearn %}active{% endif %}">
                        </span>
                    </a>

                    <!-- picure -->
                    <a href="#">
                        <img src="{{ curWord.image.url }}" class="img-responsive" style="width: 100px; float: left; margin-right: 10px;">
                    </a>

                    <p> <strong> Type:  </strong> {{ curWord.type}}</p>
                    <p> <strong> Meaning:  </strong> {{ curWord.meaning}}</p>
                    <p><strong> Pronunciation: </strong> {{ curWord.pronunc}}</p>
                    <!-- audio -->
                    <a target="_blank" href="{{ curWord.audio.url }}">
                        <button type="button" class="btn btn-success btn-sm">
                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                        </button>
                    </a>

                    <a href="{% url 'testEng:word-update' curWord.id %}">
                      <button type="button" class="btn btn-default btn-sm">
                          <span class="glyphicon glyphicon-edit"></span> &nbsp; Edit
                      </button>
                     </a>


                    <!-- Delete -->
                    <form action="{% url 'testEng:word-delete' curWord.id %}" method="post" style="display: inline">
                        {% csrf_token %}
                        <input type="hidden" name="word_id" value="{{word.id}}"/>
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-trash"></span> &nbsp; Delete
                        </button>
                    </form>

                </li>
                <br/>
            {% endfor %}
            <!--<input type="submit" value="markTolearn" >-->
        </ul>
</form>

</div>
{% endblock %}

testEng/templates/testEng/dictionaryTolearn.html
{% extends 'testEng/base.html' %}
{% block title %}Dictionary{% endblock %}
{% block body %}
<div class="container">
        <ul>
            {% for curWord in all_words %}
                <li>
<h3>{{curWord.name}}</h3>

                    <a href="{% url 'testEng:tolearn' curWord.id %}" class="btn-tolearn">
                        <span class="glyphicon glyphicon-star {% if curWord.tolearn %}active{% endif %}">
                        </span>
                    </a>

                    <!-- picure -->
                    <a href="#">
                        <img src="{{ curWord.image.url }}" class="img-responsive" style="width: 100px; float: left; margin-right: 10px;">
                    </a>

                    <p> <strong> Type:  </strong> {{ curWord.type}}</p>
                    <p> <strong> Meaning:  </strong> {{ curWord.meaning}}</p>
                    <p><strong> Pronunciation: </strong> {{ curWord.pronunc}}</p>
                    <!-- audio -->
                    <a target="_blank" href="{{ curWord.audio.url }}">
                        <button type="button" class="btn btn-success btn-sm">
                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                        </button>
                    </a>

                    <a href="{% url 'testEng:word-update' curWord.id %}">
                      <button type="button" class="btn btn-default btn-sm">
                          <span class="glyphicon glyphicon-edit"></span> &nbsp; Edit
                      </button>
                     </a>

                    <!-- Delete -->
                    <form action="{% url 'testEng:word-delete' curWord.id %}" method="post" style="display: inline">
                        {% csrf_token %}
                        <input type="hidden" name="word_id" value="{{word.id}}"/>
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-trash"></span> &nbsp; Delete
                        </button>
                    </form>
                </li>
                <br/>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

testEng/templates/testEng/index.html
{% extends 'testEng/base.html' %}

{% block body %}
<div class="container">
        {% csrf_token %}
        <form action="{% url 'testEng:testing' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">
                            <span class="glyphicon glyphicon-pencil"></span>&nbsp; Create a test
                        </button>
        </form>
        <ul>
            {% for quest in all_questions %}
                <li><a href="{% url 'testEng:detail' quest.id %}"> {{quest.question}} </a></li>
            {% endfor %}
        </ul>
</div>
{% endblock %}

testEng/templates/testEng/registration_form.html
{% extends 'testEng/base_visitor.html' %}
{% block title %}Register{% endblock %}

{% block body %}

<div class="row">
    <div class="col-xs-4 col-xs-offset-4">
        <div class="panel panel-default">
            <div class="panel-body">
                <h3>Create a new account</h3>
                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'testEng/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="panel-footer">
                Already have an account? <a href="{% url 'testEng:login_user' %}">Click here</a> to log in.
            </div>
        </div>
    </div>
</div>
{% endblock %}

testEng/templates/testEng/topic.html
{% extends 'testEng/base.html' %}
{% block title %}Topic{% endblock %}
{% block body %}
{% csrf_token %}
<div class="container">
        <ul>
            {% for topic in all_topics %}
                <li>
                    <a href="{% url 'testEng:detail-topic' topic.id %}">
                        <h3>{{topic.name}}</h3>
                    </a>
                    Posted by {{topic.user}}
                </li>
                <br/>
            {% endfor %}
        </ul>
    </div>
{% endblock %}